### ISSUE TITLE
OpenID Connect and Bearer Token on the same paths

### ISSUE THREAD

**Issue by takesson** [pingidentity/mod_auth_openidc#102]
We have a Content Management System that we would like to protect with OpenID Connect. The system provides many REST services that are consumed by both Web browsers and native applications. 

A concept I am trying to configure is having the Native Apps authenticate with JWT as a Bearer token and let Browsers do OIDC on the same paths. 

I have successfully configured both cases on separate paths. Is it possible to combine them on the same path?

Thanks!

**Comment by zandbelt** [comment]
No that is not possible since you'd either indicate `AuthType oauth20` or `AuthType openid-connect` and they're mutually exclusive; I can hardly imagine though that a well designed system CMS need that: I don't see it as good practice that the same endpoint returns HTML content for browsers and API data for non-browsers; a well-designed system would have endpoints/paths that are APIs separate from browser facing paths. It should be noted that it is perfectly possible to dissect the two under the same root, say `/CMS` and divide in to `/CMS/API-A', `CMS/API-B` etc. as APIs and `/CMS/portal' for browsers. IMHO it complex and redundant to distinguish the two based on the incoming token instead of its inherent properties, and having to do de-multiplexing further up the stack a 2nd time.

**Comment by takesson** [comment]
I don't necessarily see it as bad practice to use the same endpoint for both Browsers and API consumers. I think it is quite common for JAX-RS applications where the Browser UI is more or less also a consumer of the API. This is not a new application so the design decisions have already been made so to speak.

I am also looking at securing Subversion, where the Browser and the Subversion clients share the same endpoints.

I have also considered the cookie but I feel that the Bearer token concept is cleaner for API consumers. Do you think it would make sense to share the Cookie from the Browser with native app API consumers?

What would you say is the problem with validating a Bearer token if present in the Authorization header and otherwise do normal `AuthType openid-connect` on a single path?

**Comment by zandbelt** [comment]
We agree to disagree on the design approach (and on JAX-RS/subversion for that matter ;-))

I think sharing that cookie from the browser with a native client would result in the same: not a very clean design but it achieves want you are looking for.

Remember that mixing OAuth clients with OpenID Connect SSO is likely to introduce confusion because it mixes the Client and Resource Server roles. You're also bound to use `Require claim` statements that assume the same claims are present in access token verification results as in ID tokens, which is conceptually quite different.

Having said that: if you can come up with a patch that introduces a new `AuthType` that combines the behavior, I would consider including it. It would not be a big effort to do this as the current code should easily allow for building it out. I am concerned about undesired side effects though so I would like it to be disabled by default and I would like users to very explicitly enable this.

**Comment by takesson** [comment]
Say that we have a web application serving both native applications and a single-page web UI. A very common use-case the last few years. What is, in your opinion, the harm / unclean design in using the same API endpoints from both the SPA and the native applications?

I had a look into the code of the module and considered some of the configuration scenarios again. I understand your desire to separate the Authentication (OIDC) scenarios and Authorization (OAuth) scenarios. To some extent the lines started to blur when introducing local JWT access token validation which provides very similar capabilities/information as OIDC (and shares some configuration statements with OIDC). 

I would like to explore implementing an `AuthType` that combines OpenID Connect with JWT Bearer token validation but still confine remote validation of opaque tokens to `AuthType oauth20`. 

Thoughts? Do you prefer a new/separate `AuthType` rather than optionally doing JWT Bearer token validation in the `AuthType openid-connect`?

**Comment by zandbelt** [comment]
I am ok with two applications using the same API endpoints: they both can use an OAuth access token to do so. If however an API to a client (acting on behalf of a user) is served on the same path as HTML to a browser (where the user is authenticated), semantics of OAuth and OpenID Connect are mixed as is content. Your conclusion that JWT bearer token validation and ID Token validation are blurring the lines demonstrates that: the code may have overlap but the semantics don't.

But as mentioned in my previous answer: feel free to create a fork and PR with a new AuthType and I will consider including it based on how cleanly it can be applied to the existing code paths.

**Comment by zandbelt** [comment]
On the "feature" branch now and will be part of 2.2. See: https://github.com/pingidentity/mod_auth_openidc/wiki/Single-Page-Applications#allowing-both-oauth-20-and-openid-connect
