### ISSUE TITLE
OIDCUnAuthAction and Google 2-step Verification

### ISSUE THREAD

**Issue by michaelsse** [pingidentity/mod_auth_openidc#104]
In the case of (a)a user who has Google 2-step verification turned on and (b) a site/location/directory that should deny access to that user and (c) OIDCUnAuthAction having the value of "auth", mod_auth_openidc acts as though the value of OIDCUnAuthAction were set to "401", giving the user no opportunity to login with another account.

**Comment by zandbelt** [comment]
That is intentionally: it usually does not happen that the user has different accounts with the same OP; also: in many cases, having SSO in place, the user would not even be prompted for a different account, it would just re-use the one that you're logged in to and would introduce a loop.

FWIW: I believe the issue is unrelated to a) having 2-step verification turned on.

At this point I don't feel inclined to build in an exception for Google accounts but I may consider taking patches.
