### ISSUE TITLE
JWT was issued more than 1200 seconds ago

### ISSUE THREAD

**Issue by elpito** [pingidentity/mod_auth_openidc#123]
I'm going to use mod_auth_openidc in our apache einvironment, but after a few minutes (3-8), I get this errror:

```
oidc_oauth_validate_jwt_access_token: successfully parsed JWT with header: {"kid":"5d","alg":"ES256"}, referer: ...
oidc_proto_validate_iat: "iat" validation failure (1457701071): JWT was issued more than 1200 seconds ago
```

We are using PingFederate as IDP. I saw, this can be a problem with times on the involved servers, but I'm sure, this is not the case here. For testing, I increased the `OIDCIDTokenIatSlack` parameter, but as shown, this does not solve the problem.
Here my configuration:

```
   OIDCOAuthSSLValidateServer Off
        OIDCCacheType shm
        OIDCIDTokenIatSlack 1200
        OIDCCacheDir /var/cache/httpd/mod_auth_openidc/cache
        # 24 hours:
        OIDCSessionInactivityTimeout 86400
        OIDCOAuthVerifyJwksUri https://<PingFederate server>:3000/pa/oidc/JWKS
        OIDCOAuthRemoteUserClaim sub
        <IfModule mod_dav_svn.c>
                SVNCacheRevProps on
                <Location /svn>
                        Authtype oauth20
	                OIDCOAuthAcceptTokenAs cookie:PA.global
	                Require valid-user
                </Location>
               ...
        </IfModule>
```
Thank you for helping here....

**Comment by zandbelt** [comment]
You're using PingAccess in front of mod_auth_openidc, passing the cookie on each request that is made. That cookie stays the same (at least the issuance timestamp stays the same). You'll have to make sure that the  `OIDCIDTokenIatSlack` parameter set to whatever you want the lifetime of the token to be. Note that `OIDCSessionInactivityTimeout` only is relevant in OIDC scenarios' where a real session is created.

**Comment by zandbelt** [comment]
Did that help?

**Comment by elpito** [comment]
Yes, that helped. Sorry for late answer. Setup of OIDCIDTokenIatSlack variable solved this problem. Why is the default value so small (600)?

**Comment by zandbelt** [comment]
The value is small because it is really for the ID tokens that OpenID Connect provides, in which case the token (JWT ID Token) is presented only once, then consumed and a session is created using a session cookie. 

In your (pretty new) use case, you use a generic JWT as an access token (quite different from an ID token) that you repeatedly send to the module (much like a session cookie) and the interpretation of the `iat` becomes different.

What really should be done is to not use the same configuration primitive for the two types of tokens, but I'm a bit reluctant to introduce yet another configuration directive whilst it can be solved by picking the right value for the right use case. I hope that all makes sense.
