### ISSUE TITLE
Having an issue with verifying signatures

### ISSUE THREAD

**Issue by cfonze** [pingidentity/mod_auth_openidc#133]
[Tue Apr 19 13:01:18.667495 2016] [auth_openidc:error] [pid 10076] [client 129.42.208.179:22800] oidc_proto_jwt_verify: JWT signature verification failed: [src/jose/apr_jws.c:587: apr_jws_verify]: could not verify signature against any of the (1) provided keys\n, referer: https://idaas.iam.ibm.com/idaas/mtfim/sps/authsvc?PolicyId=urn:ibm:security:authentication:asf:basicldapuser
[Tue Apr 19 13:01:18.667541 2016] [auth_openidc:error] [pid 10076] [client 129.42.208.179:22800] oidc_proto_parse_idtoken: id_token signature could not be validated, aborting, referer: https://idaas.iam.ibm.com/idaas/mtfim/sps/authsvc?PolicyId=urn:ibm:security:authentication:asf:basicldapuser

**Comment by zandbelt** [comment]
What does the configuration of your OpenID Connect provider looks like? It would also be convenient to turn on debug logging so that you can see what algorithm was used to sign the id_token (so we know what key to look for).

**Comment by cfonze** [comment]
Thank you for the quick response.  How do you turn on debug logging?
Here's the configuration: (I erased the clientID and secret of course)
OIDCCryptoPassphrase 12312312113
OIDCRedirectURI https://ims-jabber.cloud9.ibm.com/protected/redirect_uri
OIDCProviderIssuer https://idaas.iam.ibm.com
OIDCProviderAuthorizationEndpoint https://idaas.iam.ibm.com/idaas/oidc/endpoint/default/authorize
OIDCProviderTokenEndpoint https://idaas.iam.ibm.com/idaas/oidc/endpoint/default/token
OIDCClientID xxxxxxxxxx00
OIDCClientSecret xxxxxxxxxxx00
OIDCClientName Apache-Test

<Location /protected/>
   AuthType openid-connect
   Require valid-user
</Location>

**Comment by zandbelt** [comment]
set `Loglevel` to `debug`

You have not configured a JWKS URI (`OIDCProviderJwksUri `) so only HMAC signed tokens can be validated. Perhaps your provider uses an assymmetric algorithm to sign the tokens (`RS256` is the default) and to validate those tokens, the module need to know about the public key of the provider. You can do that with `OIDCProviderJwksUri`.

**Comment by cfonze** [comment]
Thank you.  My provider doesn't currently have a uri for the JWK but I was able to get the JSON from the provider where I can serve it on my own site for validation.  Works well now.  Thanks again for your help.

**Comment by Triton-oidc** [comment]
Hi,
i managed to make it work exposing manually a json like cfonze suggested

> OIDCProviderJwksUri https://localhost:4443/static-certs

But i'd like to make it work with the
OIDCOAuthVerifyCertFiles option
I put in the configuration file :
> OIDCOAuthVerifyCertFiles 9k34qEgMyB_IEafhcNQ6vBmy3c9tuyQT2eVos8I1w4#/etc/pki/tls/certs/jks-pub-key.pem

> openssl x509 -in /etc/pki/tls/certs/jks-pub-key.pem -text -noout
return the correct information about the certificate

But i got in the logs : 

> oidc_proto_jwt_verify: JWT signature verification failed: [src/jose.c:924: oidc_jwt_verify]: could not find key with kid: N9k34qEgMyB_IEafhcNQ6vBmy3c9tuyQT2eVos8I1w4\n

What seems strange is the '\n' at the end of the kid in the error message
Am i using the correct syntax ?

I do this because my apache is not allowed to contact the IDP (keycloak in my example)

Thanks for the help

**Comment by zandbelt** [comment]
9k34qEgMyB_IEafhcNQ6vBmy3c9tuyQT2eVos8I1w4 does not seem equal to N9k34qEgMyB_IEafhcNQ6vBmy3c9tuyQT2eVos8I1w4 regardless of the "\n", the leading "N" is missing in the configuration file

**Comment by Triton-oidc** [comment]
Hi,
Thanks a for for your answer and your time.
I got the N in the configuration file

> OIDCOAuthVerifyCertFiles N9k34qEgMyB_IEafhcNQ6vBmy3c9tuyQT2eVos8I1w4#/etc/pki/tls/certs/jks-pub-key.pem

And i still have the same error.
I must have done a paste error, or i was testing putting a wrong key to see if something was going to change.

I'm using the fake local endpoint for my POC, nothing pressing for me
But if you want me to test something, or try something new, i'll do it.

Thanks again

**Comment by Triton-oidc** [comment]
3.5 month later I try again (because i can't use the localhost with the fake entrypoint anymore as the protected url is now behind a proxy, and it tries to access localhost using the proxy)

still got the same error.

I still think that's the "\n"

> OIDCOAuthVerifyCertFiles wNn-bWHlMi5U5NyhG76NeAhRX586kmDZ-cjlyCZ-Rqw#/config/export/public.pem

error message :

> could not find key with kid: wNn-bWHlMi5U5NyhG76NeAhRX586kmDZ-cjlyCZ-Rqw\n

The IDP is keycloak maybe it's adding a "\n" somewhere
but it's working when i use the OIDCProviderJwksUri method
The proxy is on a Linux
if you wish me to try something, of if you have a clue that would be great

Until then i'll try updating the module and not naming the KID

Thanks

**Comment by zandbelt** [comment]
`OIDCOAuthVerifyCertFiles` is for verifying a JWT access token in an OAuth 2.0 RS setup whereas you are looking to validate an `id_token` in an OpenID Connect RP setting.

Since you're using Keycloak you should be able to follow:
https://github.com/zmartzone/mod_auth_openidc/wiki/Keycloak

**Comment by Triton-oidc** [comment]
Thanks a lot for the information !
My Apache cannot join the keycloak server (it will only receive tokens from the keycloak through the browser)
I managed to replace the OIDCProviderMetadataURL using 
OIDCProviderIssuer
OIDCProviderAuthorizationEndpoint
OIDCProviderJwksUri
and i'd like to replace the OIDCProviderJwksUri config with a link to a file on the server (didn't saw that on the link)
Instead of creating a fake endpoint locally (because when i use a proxy, even the localhost uses the proxy, and i have no wish to expose this endpoint)

If you tell me it's not possible, it will help me a lot (i won't spend any more time searching)

Thanks

**Comment by zandbelt** [comment]
`OIDCProviderJwksUri` must be a https URL so you'll have to reconfigure your proxy to expose this endpoint or serve it from a different server; this may be as simple as proxying to:
```
JSON='{"iss": "https://example.org", "more": "data" }' ; while true; do { echo -e "HTTP/1.1 200 OK\r\n\r\n${JSON}"; } | nc -l 8080; done
```

**Comment by Triton-oidc** [comment]
Thanks a lot for your quick answers !
i know i'm on the right path now.

**Comment by Rogers-Etcet** [comment]
Hi,

I am trying to setup the auth_openidc apache module to be a RP using an openid server.
I face several issues that are most certainly because of my miss of informations on parametrizing
the module.

I have some questions :
1) Where can I get some accurate informations about hosto setup this module ?

2) My endpoint that serves le keys is never called, I set correctly this :
    OIDCProviderJwksUri https://127.0.0.1:8000/certs
    in my apache app configuration file.

3) I tried to use parameter « OIDCOAuthVerifyCertFiles Toto1 /etc/apache2/Toto1.pem ».
    I suppose that the key is loaded because if the file does not exist apache2 will not start.
   However when my authorize endpoint redirects the enduser to the redirect_uri with an
   HTTP cookie mod_auth_openidc_state_XXXXXXX containing an hmac of header { "alg": "HS256", "enc": "JWT", "kid":"Toto1" } and payload { ‘iss’: …, ‘auth’ : … , ‘exp’:…, ‘iat’ :…, ‘sub’ :…, ‘aud’ :… }, well apache2 tells me he did not find any ‘Toto1’ key.
   Also he never tries to get the key from my configured  OIDCProviderJwksUri endpoint (as told in 2) ).
   a) I am searching for days the issue about unknown key. I tried removing ‘kid’ :’Toto1’ from the header.
      What is the problem ?
 b) On Hmac sign, the server uses the clientSecret, is it correct ?

4) The parameter OIDCStateCookiePrefix when defined in the configuration file leads to an error and
 apache2 will not start.
   Is it a problem of version ? I installed the apache module from Ubuntu, I know sometime
   the version is not accurate ...

5) Where can I get samples of data exchanged during redirection to redirect_uri ? Or RFC explaining the exanges between RP and OP ?

So … lot of questions …

Regards

-Rogers

Attach files of my apache conf and MetaData returned by the OP.
[conf.txt](https://github.com/zmartzone/mod_auth_openidc/files/9394204/conf.txt)
[metajson.txt](https://github.com/zmartzone/mod_auth_openidc/files/9394206/metajson.txt)
