### ISSUE TITLE
Need an option to authenticate on call to jwks_uri

### ISSUE THREAD

**Issue by therealcmj** [pingidentity/mod_auth_openidc#135]
I have an OP that requires authentication (in this case a bearer token) in order to access the jwks_uri. I can and will be happy to write the necessary code. But before doing that I thought I should ask:
* is that something you'd accept a pull request for?
* what would you want such a setting to be named and contain?

I see three possible options - (A) the token, (B) a value for the authentication header, or (C) an entire header - name and value.

For example if the URL required:
GET /jwk HTTP/1.0
Host: www.myopenidcprovider.com
Authorization: Bearer foo

Option A would mean that the setting would be "foo"
Option B would mean that the setting would be "Bearer foo"
Option C would mean that the setting would be "Authorization: Bearer foo"

**Comment by zandbelt** [comment]
I'm not very keen on it: IHMO it is atypical use of `jwks_uri` (as that should contain only public information and your use case shifts the problem to how you'd obtain the bearer token) and it is the first time that I've come across it in over 2 years.

Having said that it should not be too difficult to come up with a config setting just like `registration_token` in `struct oidc_provider_t` although that one is available in multi-provider configs only.

You'd pass that token (set as in option A) to the `oidc_util_http_get` call in the `oidc_metadata_jwks_retrieve_and_cache` method.

Depending on how clean the patch is I would pull it; otherwise you may still maintain it in a fork until more demand is shown.

**Comment by therealcmj** [comment]
I agree that it's atypical but unfortunately it's a use case that I'm currently facing. The only other workaround I have available today would be to configure the module to use a proxy server and then have the proxy inject the token into the request. But that seems like a messier solution.

I have the necessary code already written, I just didn't want to send an unsolicited pull request if wasn't something you were interested in adding to the main code line.

**Comment by zandbelt** [comment]
If you have a PR I'll take a look, otherwise I'll close it.

**Comment by therealcmj** [comment]
Unfortunately I think that for now the best course of action is to close it. The situation that gave rise to this need is somewhat complex and may eventually go away. If I can come up with a generic way to do this that isn't too messy I'll either reopen this issue or open a new one. Thanks!
