### ISSUE TITLE
Any way to make claims on objects?

### ISSUE THREAD

**Issue by wobenshain** [pingidentity/mod_auth_openidc#178]
If I have a piece of metadata that's an object, is there a way to make a claim on its properties? For instance, if my app_metadata look like:

{
  "my_app": {
    "read": true,
    "update": false
  }
}

Is there a way I could write a claim that equates to?: my_app.update == true

**Comment by zandbelt** [comment]
there's no way to do that right now, only simple non-nested claims are supported today

your proposal would require some xpath equivalent and a perhaps an expression language around JSON which is more than exists today

Your only option today is that the application parses the JSON object and enforces the expression on its own.

**Comment by hkeeler** [comment]
If you do want to implement this at some point, you should check out [`jq`](https://stedolan.github.io/jq/).  It has a very full-featured JSON query language.  It is generally used as a command-line tool, but it looks like there is a [`libjq`](https://github.com/stedolan/jq/wiki/C-API:-libjq) you could incorporate into this project.

**Comment by zandbelt** [comment]
This functionality can now be enabled by explicitly providing the `--with=jq=<dir>` flag when compiling from source:
https://github.com/pingidentity/mod_auth_openidc/commit/7728fbd1115af179bfd2b0b3d5ed424a7751b2f9

This adds the option for a `Require claims_expr <jq-expression>` directive where the expression must return a boolean value. Note that this operates on the claims JSON object rather than the flattened headers/environment variables.

Sample expression:
```apache
Require claims_expr '.aud == "ac_oic_client" and (.scope | index("profile") != null)'
```
Full documentation will be provided once this functionality is enabled by default. At this point in time the `libjq` dependency provides challenges across various distributions so it cannot easily be included by default.
