### ISSUE TITLE
Trying to implement a custom OP Discovery page

### ISSUE THREAD

**Issue by anthnd** [pingidentity/mod_auth_openidc#190]
Hello,
I'm trying to integrate OpenID Connect into Request Tracker (an email ticket tracking system) for my work, but I'm having some problems with providing the right login setup that I planned on integrating.
Request Tracker already has its own login system and I'm building OpenID Connect on top of it. It has a built-in feature to authenticate users based on comparing the value set for REMOTE_USER to its internal database of users. What I want is for when users visit the RT Login page, they also have an option to use Google Sign In - for example. Customizing the RT login page is a trivial matter so providing the front-end sugar is no problem. What I'm having a problem with are the things going on in the background.

Here's my openidc.conf file for reference - it's pretty minimal since my knowledge of Apache configuration is still rather limited:

```
OIDCMetadataDir /opt/software/rt/etc/OIDCMetadata

OIDCRedirectURI http://localhost/oauth2callback
OIDCCryptoPassphrase password

OIDCRemoteUserClaim email
OIDCScope "email"

<Location />
    AuthType openid-connect
    Require valid-user
    LogLevel debug
</Location>
```

With this set up, when I go to localhost, I get the nice and ugly default OP Discovery page, but it serves its purpose exactly as I want EXCEPT for the fact that I can't use Request Tracker's login system.
So I looked into an external discovery page using OIDCDiscoverURL, but from what I understand, this is an external page that basically has no relation to the original website?
What I want to implement is a custom discovery page **on localhost**. Where I can set up the default login and throw in the appropriate links for other sign in options. I've tried many variations of my config and I'm still stuck with this problem in one way or another.
This seems like something that should surely be fairly simple to set up, but I just can't figure it out.

I would appreciate any help to get me going.

**Comment by zandbelt** [comment]
You can use `OIDCDiscoverURL` that points to a custom discovery/login page that shows both links to OIDC providers as well as a local username/password login, see: https://github.com/pingidentity/mod_auth_openidc/wiki#12-how-can-i-customize-the-idp-discovery-or-initial-login-page

But you'll now have to mix the two authentication methods since paths protected by mod_auth_openidc need a valid session produced by the module itself. What you could do is apply `OIDCUnAuthAction pass` (see: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L661) and have the target application redirect to the combined Discover/login page if no `REMOTE_USER` was found.

You will still need to implement the authentication process that validates username/password and sets `REMOTE_USER` if no OIDC is used from the Discovery/login page.

**Comment by anthnd** [comment]
I've implemented `OIDCUnAuthAction pass` and I think it's exactly the directive I was looking for. Everything seems to be working well so far - thank you for the help @zandbelt.

**Comment by zandbelt** [comment]
For those using `OIDCUnAuthAction pass`: be aware that using this in a secure manner requires at least version 2.1.5 https://github.com/pingidentity/mod_auth_openidc/releases/tag/v2.1.5
