### ISSUE TITLE
Use of Claim variables in rewrite / proxypass

### ISSUE THREAD

**Issue by iamambrus** [pingidentity/mod_auth_openidc#198]
On CentOS / mod_auth_openidc 2.1.2 I can't use claim* variables in rewrite / proxypass. It's really strange as the claim_* variables are available in a (test) cgi but not during rewrite. 
Relevant config entries:

OIDCScope "openid name email profile"
RewriteEngine On
RewriteMap lookup "txt:/var/my/lookup.txt"
RewriteRule ^ - [E=MYPORT::${lookup:%{HTTP:OIDC_CLAIM_specific_user_metadata}}]
ProxyPassInterpolateEnv On
ProxyPass "/" "http://127.0.0.1${MYPORT}/" interpolate
ProxyPassReverse "/" "http://127.0.0.1${MYPORT}/" interpolate

The rewritemap logic works, have verified that multiple times.
Many thanks for reading this. Otherwise mod_auth_openidc works like a charm for me.

**Comment by zandbelt** [comment]
I believe the headers may not be available in this step, but the environment variables should be, which should be available by default, see: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L598

**Comment by zandbelt** [comment]
see also this thread: https://github.com/pingidentity/mod_auth_openidc/issues/76

**Comment by iamambrus** [comment]
Thanks for the tips and quick reply! It does not appear to be set, even if setting OIDCPassClaimsAs environment
Read through the the recommended thread but AFAIK all that happens after rewrite/proxypass does its thing. Any other directions appreciated.

**Comment by zandbelt** [comment]
I'm pretty sure they would be available (from other threads like https://groups.google.com/forum/#!topic/mod_auth_openidc/d3mFE4V4Ujs), certainly for ProxyPass even the headers are available, but I would have to reproduce this to verify.

Remember the environment variable would be called `%{OIDC_CLAIM_specific_user_metadata}` not `%{HTTP:OIDC_CLAIM_specific_user_metadata}`

**Comment by zandbelt** [comment]
I am able to see mod_rewrite do the right thing, i.e. set the MYPORT variable, when I configure:

```Apache
RewriteEngine On
RewriteMap lookup "txt:/var/my/lookup.txt"
RewriteRule ^ - [E=MYPORT:${lookup:%{ENV:OIDC_CLAIM_email}}]
```

Note that you have an superfluous `:` in your expression.

I'm not able to make this work with `ProxyPass` though but I assume that is up to the interaction between those modules, not mod_auth_openidc.

**Comment by iamambrus** [comment]
yes @zandbelt that's my conclusion as well. Thanks for your feedack! However even though you can proxy with the rewriteengine, you would need proxypass. So I resorted to a workaround but it's fine, mod_auth_openidc does take care of the heavy lifting. Cheers!

**Comment by xwen001c** [comment]
I am trying to mimic the working example in Zandbelt's last comment but no success so far. I have one more step to set the Authorization header (base64 ignored for now). Here is the config I have:
 
        <Location /oauth2/>
                AuthType openid-connect
                Require valid-user
                ProxyPass  http://my.host.url/ nocanon
                ProxyPassReverse http://my.host.url/

                RewriteRule ^ - [E=AUTHNXP:%{ENV:OIDC_CLAIM_sub}]
                RequestHeader set Authorization "Basic %{AUTHNXP}e"
        </Location>

TCPDump shows:             Authorization: Basic

without the value of ENV:OIDC_CLAIM_sub. But I can see the http header OIDC_CLAIM_sub in the tcpdump with the right value.

My goal is to get the value of ENV:OIDC_CLAIM_sub, base64 encode it and set the result to Authorization header and forward to backend.

Any suggestion where I am doing wrong?

Thanks,

**Comment by zandbelt** [comment]
Well, I mentioned in that last comment "I'm not able to make this work with ProxyPass" so that would be it. I also don't see how you would be able to apply base64 encoding to it.

**Comment by xwen001c** [comment]
Sorry I missed that part.

The base64 part can be done with a rewriterule like: 

RewriteMap base64map "prg:/usr/bin/base64"
RewriteRule .* - [E=AUTHN:${base64map:%{LA-U:REMOTE_USER}:%{LA-U:REMOTE_PASS}},NE]  

as claimed here: http://serverfault.com/questions/647591/apache-as-authentication-proxy

Thanks for the quick response.

**Comment by zandbelt** [comment]
I was able to do this using:
````apache
RewriteMap base64map "prg:/tmp/base64"
RewriteRule ^ - [E=AUTHNXP:${base64map:%{HTTP:OIDC_CLAIM_sub}}]
RequestHeader set Authorization "Basic %{AUTHNXP}e"
````
I needed a special script that turns off buffering:
````perl
#!/usr/bin/perl
use MIME::Base64 qw(encode_base64);
$| = 1;
print encode_base64(<STDIN>);
````

**Comment by xwen001c** [comment]
Something interesting happened. I used your base64 script and configuration as:

                RewriteEngine on
                RewriteMap base64map "prg:/usr/local/bin/base64"
        <Location /oauth2/>
                AuthType openid-connect
                Require valid-user
                RewriteRule ^ - [E=AUTHNXP:${base64map:%{HTTP:OIDC_CLAIM_sub}:}]
                RequestHeader set Authorization "Basic %{AUTHNXP}e"
                ProxyPass  http://my.gerrit.host:8080/ nocanon
                ProxyPassReverse http://my.gerrit.host:8080/
        </Location>

        AllowEncodedSlashes On
        ProxyPass /  http://my.gerrit.host:8080/ nocanon
        ProxyPassReverse /  http://my.gerrit.host:8080/

With the above configuration, I DID get the right Authorization header sent from Apache to my Gerrit listening on port 8080. However, somehow this rewriting rule only works once per Apache session. If I run my test the second time, I will not have the right Authorization header, only see empty 'Authorization Basic'. If I restart Apache, I will observe the exactly above. (You may think this should work for me at least for the first user, but not since somehow Apache needs to forward two requests, one to '/', the other to '/login/' of gerrit. And the first one to '/' will contain the right header but the second one to 'login' will not due to above mentioned rewriting-rule-only-work-once problem. But it looks like it can work with ProxyPass at least once. 

Any comments, ideas?

**Comment by zandbelt** [comment]
Interestingly enough I observe the same but the problem seems to be in the mapping rather than in the interaction between `mod_rewrite` and `mod_auth_openidc`.

In my case I can see that the 2nd time around the mapping is called (again) with the right `key`, but no value is returned. So the input obtained from the headers is OK. Also when I use a simple lookup table i.e `RewriteMap base64map "txt:/tmp/lookup.txt"` it all works reliably. You should be able to confirm that as well by setting `LogLevel rewrite:trace8`

If confirmed it should be a matter of finding the right tool/script to do the base64 conversion. Mine has a few problems with buffering of stdin/stdout.

**Comment by xwen001c** [comment]
@zandbelt You are absolutely correct that it is the script. Here is what I have and it works for me now in the context of ProxyPass:

#!/usr/bin/perl
use MIME::Base64 qw(encode_base64);
$| = 1;
while($a = <STDIN>) {
        print encode_base64($a);
}

The script starts once per Apache session and is used by the following rewrite rule calls. Hence a 'while' look did the trick.

Thank you very much for all the help!
