### ISSUE TITLE
statically linked module possible?

### ISSUE THREAD

**Issue by samba2** [pingidentity/mod_auth_openidc#208]
Hi,

First of all thank you very much for your work. I had no difficulties at all to integrate the module using a recent SUSE Linux platform. The wiki as well as the logging where really helpful. I was expecting much more trouble. 

However, my production system is on a rather old version of SUSE so I ended up building Apache httpd myself. To get mod_auth_openidc running I installed + compiled all the required dependencies (openssl, jansson, cjose, curl). Beside the manual effort also this worked fine and Apache is now running with mod_auth_openidc  on an SUSE 11 SP2 system.

Now the question: _To easy my production rollout (more than one system) I was hoping that there is a way to statically link all the dependencies (openssl, jansson, cjose, curl) into mod_auth_openidc.so._ Any ideas how to do this? It's gotta be some linker flag...

Anyway, thanks again for your great work.

**Comment by zandbelt** [comment]
I'm not aware of anything easy since. I would also argue that easy product rollout can be done using scripting and possible tools like chef/puppet. That seems to be a more feasible approach that statically linking everything since it will result in conflicts when more than one module links the same dependency (e.g. openssl).
