### ISSUE TITLE
provide 32-bit binary for windows

### ISSUE THREAD

**Issue by istvano** [pingidentity/mod_auth_openidc#210]
Hi,

I am having trouble setting this up for a WIN-32 Apache. Unfortunately our developer environment must use windows for a given project hence I decided to use XAMPP to run Apache and MySQL which is really easy for the devs to use.

On the other hand on the release page I could only find a 64-bit version for windows. 
When I try to configure this module for 32-bit apache I receive the following error message.

httpd.exe: Syntax error on line 180 of C:/xampp/apache/conf/httpd.conf: Cannot load modules/mod_auth_openidc.so into server: %1 is not a valid Win32 application.

Is there way to compile the module for win32 Apache at all? if it is not that difficult is it possible to provide the 32-bit version as well as a downloadable distribution on the release page ?

Do I need to get 32-bit version of the dependencies (libcurl, jansson) as well?

Thanks for your help!

Istvan

**Comment by zandbelt** [comment]
That's a very timely question with perhaps a slightly unexpected answer:

I have provide win32 binaries in the past, for older versions; but the burden of setting up a Windows/Visual Studio environment with the right settings for Apache module compilation (it took me 3 days in the past and it got wiped out accidentally) for mod_auth_openidc and especially its dependencies i.e. not just libcurl libjansson but also libcjose by now, is very high and the ongoing maintenance/updating is just not something that can be done on a best-effort basis outside of a regular job.

That is one of the reasons why I have founded a company that offers a commercial offering around mod_auth_openidc that includes builds for "less than common" platforms. It is still in its early stage, I'll update the README.md later, but you can contact support@zmartzone.eu if you wish to open a commercial discussion about this.

I am closing the ticket here because it is not something that will be provided as part of this project. You'll see more updates about commercial support options in the near future.
