### ISSUE TITLE
how to pass keycloak roles to upstream

### ISSUE THREAD

**Issue by istvano** [pingidentity/mod_auth_openidc#216]
Hi,

It is a great module. I managed to configure it with keycloak and our upstream app. 
I can access profile into the the token upstream which is great.

I am wondering what do I need to do to be able to send the list of roles upstrewam?
in a heaader such as X-Auth-Roles or something.

if I add  the roles into the token. what do I need to do so that they get passed upstream ?

Thanks a lot!

**Comment by zandbelt** [comment]
Claims are passed in headers by default using a configurable header prefix:
https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L562

How claims are passed is configurable as well:
https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L590

Please ask these questions on the e-mail list mod_auth_openidc@googlegroups.com as indicated in the README.md instead of creating an Issue (unless there is an "issue"...).
