### ISSUE TITLE
Ubuntu 16.04 libapache2-mod-auth-openidc : Depends: libhiredis0.10 (>= 0.10.1) but it is not installable

### ISSUE THREAD

**Issue by star3am** [pingidentity/mod_auth_openidc#238]
Hi there, I am using your mod, it's an excellent mod, I cannot live without it! Thank you so much! 

I recently tried to upgrade to Ubuntu 16.04 but I am hitting a brick wall: 
libapache2-mod-auth-openidc : Depends: libhiredis0.10 (>= 0.10.1) but it is not installable

```
# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
# apt-cache search libhiredis
libhiredis-dbg - minimalistic C client library for Redis (debug)
libhiredis-dev - minimalistic C client library for Redis (development files)
libhiredis0.13 - minimalistic C client library for Redis
```
...
```
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
# apt-cache search libhiredis
libhiredis-dbg - minimalistic C client library for Redis (debug)
libhiredis-dev - minimalistic C client library for Redis (development files)
libhiredis0.10 - minimalistic C client library for Redis
```

Maybe creating a metapackage "libhiredis" with different versions will help? 

Thanks again! Please let me know if I can hep testing? 

Actually, as I type this, I realize it might not even be your problem, I should probably contact the libhiredis guys? Just leaving this here in case someone else has this problem.

Riaan

**Comment by zandbelt** [comment]
For Ubuntu 16.04 you need the "Wily" package as mentioned in the release notes https://github.com/pingidentity/mod_auth_openidc/releases/tag/v2.1.6 That version works with `libhiredis0.13`.

**Comment by star3am** [comment]
Thank you @zandbelt - Sorry I missed that part in the release notes, thank you for the reply and most of all thank you for all your effort. 

Have a great week! 

Riaan

**Comment by fong1999** [comment]
Hi! I am reaching out is to ask if you have any other versions of libhiredis that we can use.

We are having CVE with our httpd base image. When we upgrade to the latest version of httpd image, the CVE is disappeared. However, our app will not start. The error we are getting is related to redis. From the list that we can find, **libhiredis0.14 (0.14.1-4**) is the only version we can see. So we had to use the earlier version - **httpd:2.4.56-debian-ff** which work with **libhiredis0.14**.

Here is what we have currently:

`apt install -y libcjose0 libapache2-mod-auth-openidc libhiredis0.14`

Below is what we get:

❯ _**apt-cache show libapache2-mod-auth-openidc|grep Depends
Depends: libapr1 (>= 1.2.7), libaprutil1 (>= 1.4.0), libc6 (>= 2.14), libcjose0 (>= 0.4.1), libcurl4 (>= 7.16.2), libhiredis0.14 (>= 0.14.0), libjansson4 (>= 2.0.1), libpcre3, libssl3 (>= 3.0.0~~alpha1), apache2-api-20120211, apache2-bin (>= 2.4.16)**_

It specifically wants **hiredis v0.14.0**. We tried to use different version of httpd base image other than **httpd:2.4.56-debian-ff**. But we have not found one that works yet. In order to fix the CVE, we need to be able to find a newer version of libapache2-mod-auth-openidc that works with newer version of libhiredis.

I submitted a question with [hiredis github repo](https://github.com/redis/hiredis/issues/1227). They do have newer version of libhiredis. I am looking for assistance from you to find out what version of httpd and libapache2-mod-auth-openidc will work with libhiredis. Any suggestions? Thanks in advance!

Thanks,
Fong
