### ISSUE TITLE
Authentication with OAuth0

### ISSUE THREAD

**Issue by KundK** [pingidentity/mod_auth_openidc#255]
Hi,

I'm working on the POC for a future application. Since I'm new to OAuth and OAuth0, I'd like some confirmation and direction how to proceed.

We're selling theatre tickets through out own domains, whitelabel websites and integrated third party websites.
So far the integrated websites were calling our API in the backend and serving web pages to customers.
But now came a new requirement for a widget to the integrators website which would communicate with our API through AJAX. Therefore we can't use the current username/password authentication to the API.

The idea was to use OAuth and OAuth0's service in the following way:

1.The third party's backend would authenticate itself to OAuth0's and get a short term token. Simple user DB and username/password will do for start.
2. This token would be embedded into the HTML code to call the Javascript.
3. The Javascript code would call our API with the token in the header.
4. Your Apache auth_openidc module would send the token to OAuth0 to validate it
5. If validated the remote user id will be passed to the API to serve the relevant content to the JS code.

Do you think it's a valid use case? 

In my POC I've managed so far to authenticate and get id_token and access_token.
However I couldn't manage to get through auth_openidc. I've followed the guide from OAuth0's site. It isn't calling OAuth0 at all.

thanks for your help!
regards
Zsolt

**Comment by zandbelt** [comment]
I assume you're talking about Auth0 rather than OAuth0? Then I'd ask the question there. Basically you'd setup mod_auth_openidc as a Resource Server and have Auth0 issue JWT based access tokens: https://github.com/pingidentity/mod_auth_openidc/wiki/OAuth-2.0-Resource-Server#local-validation.

Please note: the issues list is meant for bug/feature requests; general questions about how the module works should go to the mailing list mod_auth_openidc@googlegroups.com
