### ISSUE TITLE
Enable re-auth support when authorization is denied on Require claim

### ISSUE THREAD

**Issue by zamd** [pingidentity/mod_auth_openidc#263]
This feature is required to enable step-up authentication as part of a security session

The use case is:

- User logs into an application and the module setup a session based on initial id_token
- User navigates to another part of the application which require higher auth assurance (i.e. extra-claims)  
- Currently the module simply **throws a 401 error when authorization is denied for Require claim**. The _authorization action_ should be configurable to at least do a re-auth, ideally with new scopes

Additional details in this thread:
https://groups.google.com/forum/#!topic/mod_auth_openidc/mvMz-IapHg0

**Comment by zandbelt** [comment]
I believe the best approach would be two-fold:
- add support for a `OIDCUnAuthzAction` primitive similar to [`OIDCUnAuthAction`](https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L700) that would specify the action to take when *authorization* fails (as opposed to *authentication* failing):
  - `401` as default (backwards compatible)
  - `403` as the more correct response type ("Forbidden")
  - `auth` in your case to send the user off to the OP
 - change the `OIDCAuthRequestParams` and `OIDCScope` primitives so that they can be applied to `Locations` and `Directories` as well as globally

**Comment by zandbelt** [comment]
added in [2.3.0rc0](https://github.com/pingidentity/mod_auth_openidc/releases/v2.3.0rc0)
