### ISSUE TITLE
[Feature request] Support for Keycloak Role permission 

### ISSUE THREAD

**Issue by ArnaultMICHEL** [pingidentity/mod_auth_openidc#297]
Hello,

First, i want to thanks the openidc team for this great work!

We are facing the same issue than here : https://groups.google.com/forum/#!topic/mod_auth_openidc/QOMMYeXt5Jc

Keycloak OAuth2 server send user's roles:
- in the access token,
- in the json structure : realm_access.roles[]

So we would like to have a base url filtered on a specific role, something like  :
<Location /myURLNeedARole>
                AuthType openid-connect
                Require valid-user
                Require claim realm_access.roles:MY_APP_ROLE
</Location>
But it's not working, i suppose the reason is mod_auth_openidc only check in the id_token

###### Environment

- mod_auth_openidc version mod_auth_openidc-2.3.1-1.el6.x86_64
- Apache version httpd-2.2.15-53.el6.x86_64
- platform/distro RedHat 6.8 x86_64

###### Expected behaviour
Choose with an openidc configuration parameter the OAuth2 token where you want to read a claim.
It should be :
- id token (by default)
- or access token
- or refresh token

My suggestion would be : 
  OIDCTokenClaimRequire [id_token|access_token|refresh_token]
  Require claim realm_access.roles:MY_APP_ROLE
Or
    Require claim realm_access.roles:MY_APP_ROLE [id_token|access_token|refresh_token]

###### Configuration and Log files
httpd logs says :
[Mon Sep 11 17:29:44 2017] [debug] src/authz.c(375): [client 10.105.71.173] oidc_authz_worker22: evaluating claim/expr specification: realm_access.roles:MY_APP_ROLE, referer: https://myserver/myapp-oidc/
[Mon Sep 11 17:29:44 2017] [debug] src/authz.c(204): [client 10.105.71.173] oidc_authz_match_claim: evaluating key "sub", referer: https://myserver/myapp-oidc/
[Mon Sep 11 17:29:44 2017] [debug] src/authz.c(204): [client 10.105.71.173] oidc_authz_match_claim: evaluating key "name", referer: https://myserver/myapp-oidc/
[Mon Sep 11 17:29:44 2017] [debug] src/authz.c(204): [client 10.105.71.173] oidc_authz_match_claim: evaluating key "family_name", referer: https://myserver/myapp-oidc/
...
[Mon Sep 11 17:29:44 2017] [debug] src/authz.c(399): [client 10.105.71.173] oidc_authz_worker22: authorization denied for client session, referer: https://myserver/myapp-oidc/

**Comment by zandbelt** [comment]
Firstly, claims from the `userinfo` endpoint and the `id_token` are combined in the set that is the union of both, and the resulting union is available to `Require claim` expressions. There are no claims associated with a refresh token (at least not by spec, that would be an implementation specific behavior).

Secondly, you should be able to access nested claims by using the syntax that you suggest:
`Require claim realm_access.roles:MY_APP_ROLE`
See: https://github.com/pingidentity/mod_auth_openidc/wiki/Authorization#nested-claims
that is available since version 2.3.0.
If this is not working then it may be due to the version of mod_auth_openidc in use or the fact that the contents of the claims are different: the logs as presented don't show the full contents of the claims so that is impossible to tell from here.

Thirdly, you can build from source with `libjq` support and create authorization rules of unlimited complexity, see: 
https://github.com/pingidentity/mod_auth_openidc/wiki/Authorization#complex-expressions

Support for `libjq` is available (when building from source) since version 2.3.0.

Since the `libjq` dependency is still tricky on a lot of platforms/distributions, it is not enabled in the binary packages by default. That will happen in due time. If you need a supported version with this feature enabled it requires a commercial discussion.

**Comment by zandbelt** [comment]
I'd appreciate it if you could confirm that the 2nd approach works for you OOTB.

**Comment by zandbelt** [comment]
Update: one can use a User Realm Role mapper to add role information to the id_token and/or the information returned from the userinfo endpoint. That information can then be used in `Require claim` directives to grant access only to users with specific roles.
