### ISSUE TITLE
No configure file in source tar file

### ISSUE THREAD

**Issue by gdkeller2549** [pingidentity/mod_auth_openidc#302]
I have downloaded the mod_auth_openidc-2.3.2.tar.gz source files to modify them on my local Linux el6 system to modify the ap_requires with the ap_register_auth_provider syntax for Apache 2.4.  Your documentation states to run ./configure, then make, and finally make install.  However there is no configure file in your tar file.

Please correct this, and/or send me the file in an email.  Thank you.

###### Environment

- mod_auth_openidc version (e.g. 2.1.5)
- Apache version (e.g. 2.4.8)
- platform/distro (e.g. Ubuntu Xenial or Centos 7)

###### Minimized example
*Minimal, complete configuration that reproduces the behavior. Use the mailing list or get commercial support to discuss your own (full) setup.*

###### Configuration and Log files
*Config and logs for the minimized example, possibly provided as attachments.*

**Comment by zandbelt** [comment]
You can use the tarball that is not generated directly from Github:
https://github.com/pingidentity/mod_auth_openidc/releases/download/v2.3.2/mod_auth_openidc-2.3.2.tar.gz

**Comment by zandbelt** [comment]
FWIW: the code is 2.4 compliant and uses `ap_register_auth_provider`. If you're running into problems you've most probably used the wrong binary module for your platform.

**Comment by gdkeller2549** [comment]
Hans,

I downloaded mod_auth_openidc-2.3.2-1.el6.x86_64.rpm for my system and installed it.  When I try to start Apache 2.4 I get the following error message:

httpd: Syntax error on line 208 of /local/apps/apache-2.4/conf/httpd.conf: Cannot load modules/mod_auth_openidc.so into server: /local/apps/apache-2.4/modules/mod_auth_openidc.so: undefined symbol: ap_requires

When I checked the source code found in mod_auth_openidc-2.3.2.tar.gz it does still have this call in mod_auth_openidc.c:

const apr_array_header_t * const reqs_arr = ap_requires(r);

If it is compliant with Apache 2.4 why is it still using the ap_requires call?

Gary D Keller
GE Healthcare, consultant

Office: 262-548-2470 (42470)
Cell:     262-497-6264

**Comment by zandbelt** [comment]
That's because the code is 2.2 compliant as well and uses the C `#ifdef` compiler construct to distinguish between the two at compilation time.

It appears that you're not running stock Redhat 6/CentOS 6 which comes with Apache 2.2 but rather one that you've upgraded manually to use Apache 2.4, see: https://access.redhat.com/solutions/445713

In that case I'd advise you to upgrade to either downgrade Apache or upgrade to Redhat/Centos 7 to use a stock binary mod_auth_openidc or indeed compile from scratch using the tarball from the link that I sent earlier.
