### ISSUE TITLE
mod_auth_openidc install not working in centos 7

### ISSUE THREAD

**Issue by joshoohaah** [pingidentity/mod_auth_openidc#45]
1. I'm using a centos 7 box (using vagrant & chef)
1. installing apache2.
1. Install dependencies (hiredis, jansson)
1. install mod_auth_openidc from rpm.
1. restart apache, which fails.

I get this error message from "systemctl status httpd.service"
`httpd: Syntax error on line 123 of /etc/httpd/conf/httpd.conf: Syntax error on line 55 of /etc/httpd/mods-enabled/mod_auth_openidc.conf: </IfModule> without matching <IfModule> section`

What do I do different to the .conf file so it is read properly by apache?

**Comment by zandbelt** [comment]
Which version are you using? When doing this with 1.7.1 there should be no reference to /etc/httpd/mods-enabled since there is no `mod_auth_openidc.conf` installed anywhere. Your error **should** be: 

    oidc_check_config_openid_openidc: one of 'OIDCProviderIssuer', 'OIDCProviderMetadataURL' or 'OIDCMetadataDir' must be set

at which point you'll need to configure the module according to the docs, usually in `/etc/httpd/conf.d`. There's only `httpd/conf.modules.d/10-auth_openidc.conf ` that gets installed on CentOS 7.

Could it be that you've installed a file from a Debian distribution package, since CentOS does not even use the `/etc/httpd/mods-enabled` directory AFAIK. Can you paste the contents of `/etc/httpd/mods-enabled/mod_auth_openidc.conf`?

**Comment by joshoohaah** [comment]
![2015-01-13 17_00_50-clipboard](https://cloud.githubusercontent.com/assets/8366405/5731141/d2d449fc-9b45-11e4-8e49-7b0ef010d8be.png)

I am in centos7.  however I do see the `/etc/httpd/mods-enabled` folder structure.  Apache works when I disable the openidc module.  however when I try to just add it in, i get that error.

FYI.  The `mod_auth_openidc.conf`  in `/etc/httpd/mods-enabled/`  is one of my own making.   It has all the customizations for the module I'm looking for.  Where should I drop these configurations then, if not in the 'mods-available' folder?  There is no `conf.d` folder

**Comment by zandbelt** [comment]
You seem to have a configuration structure that mixes elements from different distributions (my clean centos7 distro only has `conf.modules.d`) but nevertheless: since your own `mod_auth_openidc.conf` gets stuck loading, the error is in there. Could you examine/paste its contents? Looks like it is lacking an `<IfModule>` statement (although the error could also be in the  file that is including it, usually `/etc/httpd/conf/httpd.conf`.

**Comment by zandbelt** [comment]
I've double-checked the contents of the package for CentOS 7; there's no `/etc/httpd/mods-enabled` directory, so I'm concluding there's no bug in the module/package but it rather is a configuration error. Feel free to ask on the mailing list for help on that.

    # rpm -q -filesbypkg -p mod_auth_openidc-1.7.1-1.el7.centos.x86_64.rpm 
    mod_auth_openidc          /etc/httpd/conf.modules.d/10-auth_openidc.conf
    mod_auth_openidc          /usr/lib64/httpd/modules/mod_auth_openidc.so
    mod_auth_openidc          /usr/share/doc/mod_auth_openidc-1.7.1
    mod_auth_openidc          /usr/share/doc/mod_auth_openidc-1.7.1/ChangeLog
    mod_auth_openidc          /usr/share/doc/mod_auth_openidc-1.7.1/LICENSE.txt

**Comment by joshoohaah** [comment]
Thanks Zandbelt. I think you are correct.  I was loading in the `mod_auth_openidc.conf` file in that folder with my chef recipe. Centos does not like that configuration style
