### ISSUE TITLE
Error:  The OpenID Connect Provider returned an error: Error in handling response type.

### ISSUE THREAD

**Issue by MElhajj** [pingidentity/mod_auth_openidc#52]
Hi,

i am trying to install this module on debian 7. i have one OP (Gluu server), and a client apache with mod_auth_openidc.
When i try to test openid connect authentication, i get the redirection form the client to the OP, and then form the OP to the client after the authentication. I get this errors:

Error:  The OpenID Connect Provider returned an error: Error in handling response type.

in apache i get these errors:

````
[Thu Feb 26 12:47:44 2015] [error] [client 192.168.253.17] oidc_util_json_string_print: oidc_util_check_json_error: response contained an "error" entry with value: ""invalid_client"", referer: https://alaska.aduneo.com/oxauth/login?scope=openid&response_type=code&nonce=QezaEtaxvLdZcB3pAHSvzDf9vg5rkPWsRA2kxwN9feY&redirect_uri=https%3A%2F%2Fnewyork.aduneo.com%2Fprotected%2F&state=_3tSS-kt7KEsz6Unm-Y1tsZEY2s&client_id=%40%2100EB.2A19.32E4.4E23%210001%215A40.2DD3%210008%2145B9.D59A
[Thu Feb 26 12:47:44 2015] [error] [client 192.168.253.17] oidc_util_json_string_print: oidc_util_check_json_error: response contained an "error_description" entry with value: ""Client authentication failed (e.g. unknown client, no client authentication included, or unsupported authentication method). The authorization server MAY return an HTTP 401 (Unauthorized) status code to indicate which HTTP authentication schemes are supported. If the client attempted to authenticate via the Authorization request header field, the authorization server MUST respond with an HTTP 401 (Unauthorized) status code, and include the WWW-Authenticate response header field matching the authentication scheme used by the client."", referer: https://alaska.aduneo.com/oxauth/login?scope=openid&response_type=code&nonce=QezaEtaxvLdZcB3pAHSvzDf9vg5rkPWsRA2kxwN9feY&redirect_uri=https%3A%2F%2Fnewyork.aduneo.com%2Fprotected%2F&state=_3tSS-kt7KEsz6Unm-Y1tsZEY2s&client_id=%40%2100EB.2A19.32E4.4E23%210001%215A40.2DD3%210008%2145B9.D59A
[Thu Feb 26 12:47:44 2015] [error] [client 192.168.253.17] oidc_proto_resolve_code_and_validate_response: failed to resolve the code, referer: https://alaska.aduneo.com/oxauth/login?scope=openid&response_type=code&nonce=QezaEtaxvLdZcB3pAHSvzDf9vg5rkPWsRA2kxwN9feY&redirect_uri=https%3A%2F%2Fnewyork.aduneo.com%2Fprotected%2F&state=_3tSS-kt7KEsz6Unm-Y1tsZEY2s&client_id=%40%2100EB.2A19.32E4.4E23%210001%215A40.2DD3%210008%2145B9.D59A
```

the content of auth_openidc.conf:
```
OIDCRedirectURI https://newyork.aduneo.com/protected/
OIDCCryptoPassphrase password
OIDCProviderMetadataURL https://alaska.aduneo.com/.well-known/openid-configuration
OIDCSSLValidateServer Off
OIDCClientID @!00EB.2A19.32E4.4E23!0001!5A40.2DD3!0008!45B9.D59A
OIDCClientSecret 5nz4TtA2L/XrFjzfoPt4XA==
OIDCClientName newyork

<Location /protected/>
   AuthType openid-connect
   Require valid-user
</Location>
```

can you give me a hint please?

Thank you very much

**Comment by zandbelt** [comment]
Perhaps you can check the server logs since the server returns an error saying that it can't authenticate the client. This usually means that the `client_id`/`client_secret` is wrong. In your case the authentication request succeeds so the `client_id` must be right and I suspect an issue with the `client_secret`.

What strikes me is that your `OIDCClientSecret` seems to be a base64encoded value. Are you sure that that is the verbatim secret configured on the GLUU server? mod_auth_openidc is not going to base64decode the secret or anything before sending it off to the server.

**Comment by zandbelt** [comment]
Some googling suggests that the configuration on the GLUU server fixes way that the client may authenticate. Since the server publishes all methods in its Discovery metadata, **mod_auth_openidc** will pick the first method listed. E.g. the GLUU instance that I do interop testing with has 
```
    "token_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post",
        "client_secret_jwt",
        "private_key_jwt"
    ],
```
so **mod_auth_openidc** would pick `client_secret_basic`. If you have configured `client_secret_post` on the GLUU server in the settings for your client then you could change either those settings to `client_secret_basic` or change the **mod_auth_openidc** configuration to include:

    OIDCProviderTokenEndpointAuth client_secret_post

I think that should do it.

**Comment by MElhajj** [comment]
Thank you for relpy

I just wrote the password without encoding and now it works, with the authentication method:

"client_secret_basic"

Finally :)

**Comment by zandbelt** [comment]
ok, thanks for the update
