### ISSUE TITLE
Is there a way to disable mod_auth_openidc session management feature

### ISSUE THREAD

**Issue by yinchuan** [pingidentity/mod_auth_openidc#53]
Thanks for this great mod. 
I encounter a problem with the session management, mod version 1.7.2/1.7.3.
from the wiki:
> If the OP supports session management, it will automatically be used by mod_auth_openidc.

I use mod_auth_openidc to protect Zabbix，so there is no OP/RP hidden iframes. mod_auth_openidc generate new mod_auth_openidc_state_ cookie everytime page refreshes, the cookie size get larger and larger quickly, final cause 'bad request' error.

So, is there some config options to disable the session management?

**Comment by zandbelt** [comment]
I suspect this is unrelated to session management itself. Each request to a protected endpoint results in a separate `mod_auth_openidc_<id>`  to allow for concurrent request handling. That feature is useful for session management but also required in general to allow for concurrent authentication requests e.g. when multiple tabs in a browser are opened at the same time.

To determine the most useful way forward, it would be good to post a browser trace so I can analyze what is happening. I need to see exactly what type of access/pages result in this behavior.

Note that a possible solution may be to use the `OIDCReturn401` directive on paths that would not benefit from a browser redirect anyway, e.g. APIs, AJAX endpoints, or (protected) content  that is never accessed directly but only included in protected pages.

**Comment by yinchuan** [comment]
Thanks for reply so quickly. I will try OIDCReturn401.

On Sat, Feb 28, 2015 at 4:09 PM, Hans Zandbelt <notifications@github.com>
wrote:

> I suspect this is unrelated to session management itself. Each request to
> a protected endpoint results in a separate mod_auth_openidc_<id> to allow
> for concurrent request handling. That feature is useful for session
> management but also required in general to allow for concurrent
> authentication requests e.g. when multiple tabs in a browser are opened at
> the same time.
>
> To determine the most useful way forward, it would be good to post a
> browser trace so I can analyze what is happening. I need to see exactly
> what type of access/pages result in this behavior.
>
> Note that a possible solution may be to use the OIDCReturn401 directive
> on paths that would not benefit from a browser redirect anyway, e.g. APIs,
> AJAX endpoints, or (protected) content that is never accessed directly but
> only included in protected pages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pingidentity/mod_auth_openidc/issues/53#issuecomment-76516510>
> .
>



-- 
尹川 架构组SA
QQ: 254113859
微信: $QQ
Google Plus: yinchuan.blue@gmail.com

**Comment by yinchuan** [comment]
Sorry for replying lately.

I do further test and find some problem with clear unused state cookies.

1. On non-login status (cookie expires or first login) open several protected pages in different tabs and stop at Google Auth login page (means not login), every tab generate a mod_auth_openidc_state_ cookie, then close all these pages, leave the mod_auth_openidc_state_ cookies uncleaned.

2. When cookie expires, if page send multi-request to the protected page(like update graphs in Zabbix), the same thing happens as above.

3. On non-login status (cookie expires or first login) open the same page in several different tabs and stop at Google Auth login page (means not login), I must login on every tabs, just refresh the rest tabs can't let me in(because the state cookie exists).

All these problem cause by the state cookie. I hope I have made it clear!

**Comment by zandbelt** [comment]
I'm sorry but there's nothing really that is a bug or anything:

1. multiple parallel logins are supposed to create different state cookies; once you get redirected to the Provider, control over the cookie is lost from mod_auth_openidc until the browser returns from the Provider with an authorization response (either succesful or unsuccesful); by very nature of the web you can't expect cookies to be cleaned if you're not visiting the website that set them

2. "session cookie expired" will indeed trigger the same behaviour as "no session cookie", that's the intended behavior

3. that's because Google chooses to implement their login pages in this way; mod_auth_openidc is not involved at that point and cannot change the behavior you observe

What I would recommend is to create a setup in which you:

- don't open multiple browser tab before you've authenticated successfully in a single tab (that will fix 1. and 2.)
- increase the session idle timeout from the default of 300 seconds using `OIDCSessionInactivityTimeout ` so that it matches your requirements (e.g. make it valid for a day or so)

Would that help?

**Comment by zandbelt** [comment]
I'm assuming that it is OK to close this ticket?

**Comment by yinchuan** [comment]
It's OK to close this ticket.
