### ISSUE TITLE
OAuth2 documentation improvement

### ISSUE THREAD

**Issue by sourcekick** [pingidentity/mod_auth_openidc#54]
The documentation of the module should be sharpened with respect to OAuth2.

There is a part that says that the module always acts as a resource server in an OAuth2 context, the actual resources being served from an underlying system proxied by this apache module. Therefore the module supports token validation via an endpoint. So far, so good, but:

- How would an abstract integration szenario look like?
- How would a typical integration scenario look like?
- What are the supported OAuth2 grant types?
- What would be the prerequisites that provider and client must fulfill for the integration to work?
- Does the module support other steps in either grant type, such as redirecting a client to an authorization server (i.e. a login page)?

**Comment by zandbelt** [comment]
The integration options, abstract/typical/prerequisites are described here: https://github.com/pingidentity/mod_auth_openidc/wiki/OAuth-2.0-Resource-Server

There's no such thing as supported grant types since it is not a Client nor an Authorization Server; it is a Resource Server consuming Bearer access tokens only as described in the Wiki doc.

The module does not support redirecting clients to an Authorization Server since that is not part of the OAuth 2.0 specification (mostly because the client may not even be able to use a browser for the redirect) and would be a proprietary extension.

I'm I right to conclude that you're missing a link to the Wiki doc from the README.md?

**Comment by sourcekick** [comment]
Yes, such links would be helpful. Thank you for the quick clarification.
