### ISSUE TITLE
REMOTE_USER not accessable to Mod_Rewrite even when using LA-U

### ISSUE THREAD

**Issue by acp-nsimon** [pingidentity/mod_auth_openidc#55]
Hello,
to begin thank you for your excellent work on this module!

REMOTE_USER environment variable is not accessible in mod_rewrite despite the use of LA_U.
A simple exemple:
  RewriteEngine On
  RewriteCond %{LA-U:REMOTE_USER} .+
  RewriteRule . - [L,E=USEROK:1]

USEROK variable will never defined.

If i use the instructions below, i rejected despite successful authentification openidc:
 Order Deny,Allow
 Allow from env=USEROK
 Deny from all
 Satisfy All

Logs:
IP - - [03/Mar/2015:16:00:44 +0100] "GET / HTTP/1.1" 403 579 "..."
Logs without the Allow directive:
IP - USERNAME [03/Mar/2015:16:01:50 +0100] "GET / HTTP/1.1" 200 1133 "..."

There was a similar issue on mod_auth_openid: https://github.com/bmuller/mod_auth_openid/issues/2

We are on Debian Wheeze (64bits), Apache 2.2 and openidc 1.7.3

**Comment by zandbelt** [comment]
Yes, it is a know fact that construction won't work directly due to the order in which modules are called: the headers/variables set by `mod_auth_openidc` are not available in the `mod_rewrite` phase. This also holds for modules that do similar external SSO like `mod_auth_openid`, `mod_auth_cas` etc.

What you can do is apply some rewriting that makes your condition execute twice so the second time around the headers will be set and you can apply rules to them. It would look like:

    RewriteEngine On
    # a catchall that will incur an internal redirect, hitting the same path again with REDIRECT_PASS set
    RewriteCond %{ENV:REDIRECT_PASS} !1
    RewriteRule .* $1 [L,E=PASS:1]
    
    # this code is only executed the 2nd time around when mod_auth_openidc headers will have been set
    RewriteCond %{REMOTE_USER} .+
    RewriteRule .* $1 [L,E=USEROK:1]

This is based on the Apache feature that `mod_rewrite` prefixes `REDIRECT_` to environment variables on a redirects as documented here http://stackoverflow.com/questions/3050444/when-setting-environment-variables-in-apache-rewriterule-directives-what-causes.

Let me know if that (or some variant of it) works for you.

**Comment by acp-nsimon** [comment]
Hello,
unfortunately no behavior change with variables prefixed by REDIRECT_
I can not reproduce the behavior descrived in your link.

**Comment by zandbelt** [comment]
Perhaps REMOTE_USER is different. You should be able to use actual headers, like `OIDC_CLAIM_sub`. That should be set at that point, so:

    RewriteCond %{ENV:REDIRECT_PASS} !1
    RewriteRule .* $1 [L,E=PASS:1]

    RewriteCond %{HTTP:OIDC_CLAIM_sub} .+
    RewriteRule .* $1 [L,E=USEROK:1]

**Comment by zandbelt** [comment]
Perhaps you can describe what you want to achieve and I can provide the relevant access control directives using `mod_rewrite` instead of the proposed `Allow` directives.

**Comment by zandbelt** [comment]
Any progress/news on this one?
