### ISSUE TITLE
Debian package installs apache 2.2 module even if apache 2.4 is installed

### ISSUE THREAD

**Issue by billsimon** [pingidentity/mod_auth_openidc#58]
After installing the deb package on my wheezy server with apache 2.4, the module fails to load:

```
apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/auth_openidc.load: Cannot load /usr/lib/apache2/modules/mod_auth_openidc.so into server: /usr/lib/apache2/modules/mod_auth_openidc.so: undefined symbol: ap_requires
```

The deb package seems to be installing the module appropriate to apache 2.2, which still has ap_requires, rather than 2.4, where that function has been removed.

**Comment by zandbelt** [comment]
I don't think there's much that can be done here in terms of packaging: Wheezy comes with Apache 2.2 by default thus packages will be compiled for that. Since apparently you've upgraded to 2.4 you are left to compile your own packages for Wheezy/Apache 2.4 as well. I think it would be too much of a pain to support binary packages for this non-standard variant as part of this project but if anyone is interested in providing one, I'll put it up in the Releases section.

**Comment by billsimon** [comment]
Sorry about that. I thought apache 2.4 was the default because I didn't recall upgrading to that version from stock. I moved ahead by compiling from source without any difficulty. Thanks.

**Comment by zandbelt** [comment]
see e.g.: https://blog.wpkg.org/2014/06/29/building-apache-2-4-x-deb-packages-for-debian-wheezy-7-x/

**Comment by billsimon** [comment]
OK, now I see the problem -- malfunction between my ears. While I was installing Wheezy servers elsewhere, the server in question here is Ubuntu 14.04, and yes it came with apache 2.4. I installed the wheezy backport package on it...

**Comment by zandbelt** [comment]
my advice: don't do that ;-)
