### ISSUE TITLE
_ in headers

### ISSUE THREAD

**Issue by davidbernick** [pingidentity/mod_auth_openidc#71]
Hi!

Many of my claims (and some of the headers this code generates) have _ in them. Apache strips those out so they are unavailable to my application. For instance:  

OIDC_id_token  

Is unavailable to the application because Apache strips it out. Do you have a way of making "_" into "-" or a different accepted character?

**Comment by zandbelt** [comment]
You can use `OIDCClaimPrefix` as documented in https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L473

FWIW: it is not Apache that strips out these headers but apparently something else in your environment. E.g. `mod_wsgi` < v4.3.0 is known to do that.

**Comment by davidbernick** [comment]
OIDCClaimPrefix only handles the prefix. Many claims/headers have _ in them (id_token, first_name, etc). But I hear what you're saying. I'll look elsewhere down the chain to see where they're being stripped.

**Comment by zandbelt** [comment]
ouch, you're right: only the actual claims in the `id_token` and those returned from the user info endpoint will use the configured prefix; that needs a patch indeed

**Comment by zandbelt** [comment]
I'm going to leave this as a "wontfix" for the time being: the `OIDCClaimPrefix` is for the claims specifically (by default `OIDC_CLAIM_`) and I wanted to put the non-claims info (i.e. `id_token`, `access_token`, `access_token_expiry` in a different namespace which is `OIDC_` right now. In due time I could make this configurable through a separate configuration primitive but only when there's substantial demand for it and it is reopened (you would not be helped anyway because the `id_token` etc. would still have the underscores)

**Comment by davidbernick** [comment]
Yeah just as an FYI for my very specific world I modified the code manually myself in a really hacky way (after a fork) and I'm good enough for our use case.
