### ISSUE TITLE
Cookie size

### ISSUE THREAD

**Issue by davidbernick** [pingidentity/mod_auth_openidc#84]
Sometimes the Session cookies are very large (larger than 4k) causing some browsers to drop them. Is there a way to make cookies smaller? I imagine they're some encoded value that's important, but it would be nice to have them a more limited size. Any ideas?

**Comment by davidbernick** [comment]
I realize it's a function of the JSON that's being sent back. Just wondering if somehow we can make that smaller. I understand if the answer is, "no. you can't."

**Comment by zandbelt** [comment]
In the default setup the session cookie should be of constant length and quite small because it only contains a session identifier that points in to a server side cache. 

Perhaps you've used `OIDCSessionType client-cookie` to modify the default behavior and store all session information in a cookie? If so you've now ran in to the limits of that and you'll need to look in to server side caching again.

Another possible source of problems is the `state` cookie (the one that starts with `mod_auth_openidc_state_`) that contains only intermediate state kept between authentication requests and responses. That may become large if there are multiple concurrent requests outstanding.

Perhaps you're running in to one of those above?

**Comment by davidbernick** [comment]
Yes, I mean "OIDCSessionType client-cookie", sorry. The problem with using server caching is that I need to have a shared disk between all of my servers (as my servers are in a load balancer config) so they can share info. I liked the Client COokie approach because it meant the servers can be independent. It's either "share a disk for everyone" or "figure out how to make the session cookie smaller." I just didn't know if you have a way to cut off the session cookie to a certain size.

**Comment by zandbelt** [comment]
The reason for server-side caching options to exist is exactly because of the size restrictions on client side state. mod_auth_openidc provides options for using a Memcache server or a Redis server apart from the "files-on-shared-disk" option. You'll have to pick between these three, see: https://github.com/pingidentity/mod_auth_openidc/wiki/Caching
