### ISSUE TITLE
[Feature Request] add support to set session cookie age time

### ISSUE THREAD

**Issue by yinchuan** [pingidentity/mod_auth_openidc#97]
Default session cookie's max age time is `session`. I have these settings in configuration file.
```
OIDCSessionInactivityTimeout 86400
OIDCStateTimeout 60
```
IMHO, session cookie's max age time should be the same with `OIDCSessionInactivityTimeout`.

**Comment by zandbelt** [comment]
The session life time is really enforced server side. I don't see what you would achieve with that, can you explain? 

Besides that, setting an expiry/max-age on the cookie will make it persistent and survive browser restarts. That may lead to unexpected behaviour and a vulnerability since after closing the browser an attacker may take over the terminal and restart the browser within the max-age window. I'd rather stick with the behavior of a browser close removing all sessions.

Also: using max age would require resetting the value on each response, that is overhead that doesn't bring additional security.

**Comment by yinchuan** [comment]
@zandbelt Thanks for replying. I understand the points you concern about security.
In my usecase,  "makeing cookie persistent and survive browser restarts" is just what I want. So, maybe  an option to set cookie life time is a proper solution?

**Comment by zandbelt** [comment]
Yes, that could be added as a configurable option (disabled by default for security reasons).

**Comment by yinchuan** [comment]
Thanks!

> using max age would require resetting the value on each response
I can't understand this well. I think set cookie the first time user logs in is just enough, and need not to do this in the following response.

**Comment by zandbelt** [comment]
yes, using `expiry`; `max-age` is a different parameter that would need to be reset each time.

**Comment by zandbelt** [comment]
See commit 08854ff; you'd use `OIDCSessionType server-cache:persistent` and control the expiry with `OIDCSessionInactivityTimeout`.

**Comment by yinchuan** [comment]
Thanks for your great work!!!
